### ISSUE TITLE
JSSSync Command Fails When Not Assigned to a site.

### ISSUE THREAD

**Issue by kylecrawshaw** [MacDash/MacDash#16]
## New issue checklist

- [X] I have searched [existing issues](https://github.com/MacDash/MacDash/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Release Version:
- Reproducible every time? (Yes/No): Yes
- Related issues:

## Bug report
When running `python manage.py jsssync` and there are no sites the command fails with the following error:
```
django.db.utils.IntegrityError: new row for relation "jss_site" violates check constraint "jss_site_id_check"
DETAIL:  Failing row contains (-1, None).
```
#### Expected behavior
I would expect the jsssync command to continue and not try to link a site to a computer if the computer is not assigned to a site.
> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

**Comment by kylecrawshaw** [comment]
@cshepp1211 this was the issue you mentioned to me earlier. This occurs because a computer has no site assigned. This is a logic and code design issue.

**Comment by cshepp1211** [comment]
@kylecrawshaw yes, that is the error message.

**Comment by Tecnico1931** [comment]
Same issue for me

**Comment by kylecrawshaw** [comment]
@Technico1931 can you try a new branch I created to see if it fixes the issue for you?

https://github.com/MacDash/MacDash/tree/kylecrawshaw/issue-16-fix?files=1

**Comment by Tecnico1931** [comment]
@kylecrawshaw that works you should merge to master

**Comment by quovadimus** [comment]
@kylecrawshaw 
When running the new branch, I am seeing the attached issue during 'jsssync'.  It is different than the original, though still seems to be looking for a site. 

```
Traceback (most recent call last):
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: column jss_computer.site_id does not exist
LINE 1: ...computer"."real_name", "jss_computer"."building", "jss_compu...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/admin/Downloads/MacDash-kylecrawshaw-issue-16-fix/jss/management/commands/jsssync.py", line 13, in handle
    tasks.update_all_computers()
  File "/Users/admin/Downloads/MacDash-kylecrawshaw-issue-16-fix/jss/tasks.py", line 65, in update_all_computers
    update_computer(comp.get('id'), comp.get('name'))
  File "/Users/admin/Downloads/MacDash-kylecrawshaw-issue-16-fix/jss/tasks.py", line 50, in update_computer
    computer, _ = Computer.objects.get_or_create(computer_id=jss_computer_id, site=jss_site)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/manager.py", line 122, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/query.py", line 465, in get_or_create
    return self.get(**lookup), False
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/query.py", line 381, in get
    num = len(clone)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/query.py", line 240, in __len__
    self._fetch_all()
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/query.py", line 1074, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/query.py", line 52, in __iter__
    results = compiler.execute_sql()
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/models/sql/compiler.py", line 848, in execute_sql
    cursor.execute(sql, params)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/utils.py", line 95, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/Users/admin/Library/Python/3.5/lib/python/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: column jss_computer.site_id does not exist
LINE 1: ...computer"."real_name", "jss_computer"."building", "jss_compu...
                                                             ^

macdash:MacDash-kylecrawshaw-issue-16-fix admin$ 
```

**Comment by kylecrawshaw** [comment]
I wonder if that was the site that it failed on previously. Is this with the existing postgres db? Can you try recreating the db and see if that fixes it for you?

**Comment by kylecrawshaw** [comment]
Looks like the views issue can be fixed relatively easily too. I'll try to figure out what needs to be changed this week to fix that.

**Comment by quovadimus** [comment]
I created a new postgres db for this.  Also, I don't have any sites on this JSS.

**Comment by kylecrawshaw** [comment]
Technico1931 -- I think the issue for you should be fixed based on the most recent changes. Can you test?

quovadimus -- I'm going to look into your traceback a bit more later on today.
